import axios from 'axios';
const api=axios.create({baseURL:import.meta.env.VITE_API_URL||'http://localhost:5000/api',headers:{'Content-Type':'application/json'}});
api.interceptors.request.use(config=>{const token=localStorage.getItem('sams_token');if(token)config.headers.Authorization=`Bearer ${token}`;return config});
api.interceptors.response.use(r=>r,e=>{if(e.response?.status===401){localStorage.removeItem('sams_token');localStorage.removeItem('sams_user');}return Promise.reject(e)});
const resource=name=>({list:()=>api.get(`/${name}`),get:id=>api.get(`/${name}/${id}`),create:data=>api.post(`/${name}`,data),update:(id,data)=>api.put(`/${name}/${id}`,data),remove:id=>api.delete(`/${name}/${id}`)});
export const authApi={login:data=>api.post('/auth/login',data),register:data=>api.post('/auth/register',data),me:()=>api.get('/auth/me')};
export const flightsApi=resource('flights');
export const luggageApi=resource('luggage');
export const visitorsApi=resource('visitors');
export const staffApi=resource('staff');
export const transportApi=resource('transportation');
export default api;
